### ISSUE TITLE
Generating the Photon Go client with setup tutorial in README.md

### ISSUE THREAD

**Issue by zafhiel** [prisma/photongo#49]
Hi guys, I'm very amazed at this version of prisma2 with photongo I want to test, but I have a problem with generating the Photon Go client.

I try to describe all the steps to reproduce:

**New instance Ubuntu 18.04**

1. Update apt , install npm and prisma
```shell script
apt update
apt install npm
npm i -g --unsafe-perm prisma2@alpha # I try all versions
```
2. Install Golang and Photongo
```shell script
wget https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.13.5.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
go get github.com/prisma/photongo
```
3. following the steps of the tutorial setup README.md, at step 4
```shell script
mkdir app
nano schema.prisma # Paste all content from Setup Tutorial step 2
go run github.com/prisma/photongo lift save --create-db --name "init" # Works! 
go run github.com/prisma/photongo lift up # Works!
```
4. Here is the problem, i ran this command and nothnig happens, no error but does not generate my .go file
```shell script
go run github.com/prisma/photongo generate # Nothing happens
```

I try to modify the ouput here:
```
generator photon {
  provider = "photongo"
  output = "./photon/photon_gen.go"
  package = "photon"
}
```
The same result with:
```
output = "/root/app/photon_gen.go"
```

I'm trying a lot of scenarios and always in the command **generate** nothing happens, I need help!

im sorry for my english! saludos a todos!! :stuck_out_tongue_winking_eye:

**Comment by steebchen** [comment]
Please note that Photon Go is currently under heavy development and an experimental project. Some things are far from ideal right now, especially regarding documentation.

The problem you're having is due to https://github.com/prisma/prisma2/issues/934. Until this is fixed, you need to specify an absolute path for the `photongo` provider, which you can find out with `which photongo` after installing the library. For example, on Mac this would look like this: 

```
generator photon {
	provider = "/Users/luca/go/bin/photongo"
	output = "./photon/photon_gen.go"
	package = "photon"
}
```

Please note that you do not need to have NodeJS/prisma2 installed anymore.

**Comment by zafhiel** [comment]
thanks for all your comments @steebchen, works perfectly
